- hosts: spartan01
  become: yes
  remote_user: spartan
  tasks:
  - name: Instalando nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Habilitando o start do Nginx no boot
    service:
      name: nginx
      enabled: yes

  - name: Iniciando Nginx
    service:
      name: nginx
      state: started

  - name: Copiando pagina principal
    copy:
      src: index.html
      dest: /var/www/html/index.html